### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by Mayur28** [prlz77/vgg-face.pytorch#4]
Hi,

I tried following the instructions in the README but unfortunately, I am continuously encountering the following error when trying to load the model (I am on Windows):

```
Traceback (most recent call last):
  File "models/vgg_face.py", line 102, in <module>
    model.load_weights()
  File "models/vgg_face.py", line 46, in load_weights
    model = torchfile.load(path)
  File "C:\Users\mayur\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\mayur\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\mayur\AppData\Local\Programs\Python\Python36\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'numpy.ndarray'
```

Any assistance would be highly appreciated.

Thanks.

**Comment by prlz77** [comment]
Hi @Mayur28,

Unfortunately I do not have access to a windows machine right now but I just tried on linux with python 3.8.5 and pytorch 1.9 and it works correctly.

I suggest asking to the pytorch windows community and please let me know if you solve it!

**Comment by DeathSprout** [comment]
Hi @Mayur28,

I have the same problem as you(on windows),and I try to use other repo as [PyVGGFace](https://github.com/chi0tzp/PyVGGFace/) and [convert_torch_to_pytorch](https://github.com/clcarwin/convert_torch_to_pytorch/).
For the same reason failed.

If you solve the problem now, please let me know.
Any assistance would be highly appreciated.

Thanks.

**Comment by Mayur28** [comment]
Hi @DeathSprout,

I was able to resolve the issue, although, considering that this happened a while back, I cannot remember what did I do to resolve the issue. As soon as I have a few spare moments, I will look into it again and let you know what did I do to resolve the issue.

Apologies.

**Comment by DeathSprout** [comment]
Hi @Mayur28 ,

thanks , I used this vgg-face.pytorch in the Ubuntu subsystem as prLz77 said , it works well.
Maybe I'll give it a try before @  you.

Thanks for your answer.

**Comment by sdulyq** [comment]
I alse meet this problem, but when I use it in Ubuntu it works fine.

**Comment by prlz77** [comment]
@Mayur28 let us know if you remember how to fix it!
